### ISSUE TITLE
Is there a detailed documentation available for SenePy?

### ISSUE THREAD

**Issue by zhangjy859** [jaleesr/SenePy#1]
Hi, 

I'm glad to see that you have published such an outstanding tool on bioRxiv (doi: 10.1101/2023.08.30.555644). I am very interested in this tool and its details, and I would like to try it out as soon as possible. Could you please provide a detailed description and documentation for it?

Begrads

Zhang

**Comment by mousepixels** [comment]
Hi! Thank you for checking it out! 

Detailed documentation is still in progress along with some extra features.

For right now you can refer to the example usage: https://github.com/jaleesr/SenePy/blob/main/EXAMPLE_USAGE.ipynb

I also tried to make the docstring for each function descriptive.

Please let us know if you have any other questions!

Mark

**Comment by zhangjy859** [comment]
Hi @mousepixels

Thank you for your response. 

This .ipynb file provides many useful examples and it is helpful. Meanwhile, I think a well-documented might be even better in helping understand the software and use it correctly for some people. I am looking forward to further updates from you.

Begrads

Zhang
